before_install:
  - sudo apt-get -y -qq install curl make libgc-dev
  - git clone --depth=1 git://github.com/nddrylliog/rock.git -b 99x
  - (cd rock && make -s rescue)
  - export PATH=$PATH:$PWD/rock/bin
  - wget http://chipmunk-physics.net/release/ChipmunkLatest.tgz -O - | tar xz
  - mkdir prefix
  - cd Chipmunk-*
  - cmake -DBUILD_DEMOS="false" -DCMAKE_INSTALL_PREFIX=../prefix -DCMAKE_PREFIX_PATH=../prefix .
  - make install -j4
  - cd ..

script:
  - export OOC_LIBS=$PWD
  - cd samples
  - mkdir -p travis
  - rock -v hello -o=travis/hello -L../prefix/lib -I../prefix/include && LD_LIBRARY_PATH=../prefix/lib travis/hello

